### ISSUE TITLE
Start binder a rocker Dockerfile, running jupyter

### ISSUE THREAD

**Issue by cboettig** [binder-examples/r#1]
From project root:

```
jupyter-repo2docker verse
```

**Comment by benmarwick** [comment]
Very handy! Where does this go, in `runtime.txt`?

**Comment by choldgraf** [comment]
this may actually be outdated now? As R is installed if you include the MRAN date in `runtime.txt` (see the file in this repo for an example).

**Comment by choldgraf** [comment]
though maybe it's worth adding docs / a repo to show how to accomplish the same thing using the rocker project and a Dockerfile? What do you think @cboettig

**Comment by cboettig** [comment]
:+1:

**Comment by choldgraf** [comment]
Cool - I'm gonna close this as I've opened up another issue so it's a bit more discoverable:

https://github.com/jupyterhub/binder/issues/78
