### ISSUE TITLE
shiny binder link is off

### ISSUE THREAD

**Issue by choldgraf** [binder-examples/r#13]
Not sure what exactly, but here's what I see:

![image](https://user-images.githubusercontent.com/1839645/40813012-947deb84-64ed-11e8-89c8-2e0b0d9c979c.png)

The link has resolved to:

```
https://hub.mybinder.org/hub/bus-dashboard/?token=<MYTOKEN>
```

which seems wrong, since there is no pod URL in there...

Here's what the binder link in the readme points to:

```
https://mybinder.org/v2/gh/binder-examples/r/master?urlpath=shiny/bus-dashboard
```

If I do **not** include `urlPath` in the url, then it directs me to the correct URL. I can also confirm that urlPath still works fine on the jupyterlab demo repository.

cc @betatim !

**Comment by choldgraf** [comment]
Also, note that this actually happens **after** the repository loads, after redirection from `/shiny/bus-dashboard`

* to recreate, launch a binder for this repo **without** `urlPath`.
* once it loads, replace `tree` with `/shiny/bus-dashboard`
* it then redirects me to `https://hub.mybinder.org/hub/bus-dashboard/?token=<MYTOKEN>` (removing the pod-specific part of the URL)

**Comment by betatim** [comment]
Updated the link in the README this morning.

It has to be http://beta.mybinder.org/v2/gh/binder-examples/r/master?urlpath=shiny/bus-dashboard/ and it was http://beta.mybinder.org/v2/gh/binder-examples/r/master?urlpath=shiny/bus-dashboard which fails (trailing / missing).

**Comment by choldgraf** [comment]
ah hmmm, good to know...is that a bug we need to squash somewhere?

**Comment by betatim** [comment]
If it is a bug then it is in `nbserverproxy`, but I am not sure if it is a bug or expected behaviour. From a usability/user point of view I find it annoying.

**Comment by mrjoh3** [comment]
I suspect I am having a similar issue. I just can't get my app to load. The build seems to work but the URL does not. I have tried numerous variations but nothing works. It is a fairly simple shiny app and I have tried it both in the repo root directory and in an app/ folder. My app can be found here:

https://github.com/mrjoh3/georefr

any suggestions or advice would be appreciated.

**Comment by betatim** [comment]
For me `https://mybinder.org/v2/gh/mrjoh3/georefr/master?urlpath=shiny/app/` works. The important part is the trailing slash, without it it doesn't work.

**Comment by choldgraf** [comment]
@mrjoh3 did you figure this one out? wanna make sure this isn't a bug on binderhub's end

**Comment by mrjoh3** [comment]
no I am still getting the same problem the server was loading but ending in
an error message (copied below). I then tried rebuilding once more and have
included a screenshot of the setup below


An error has occurred

The application failed to start.

The application exited during initialization.


[image: Screenshot from 2018-11-30 20-45-13.png]

**Comment by betatim** [comment]
I get that error as well (application failed to start), this is a problem with the Shiny app though I think.

**Comment by mrjoh3** [comment]
I have add some extra dependant packages just in case. But the app works
fine locally and on shinyapps.io

https://mrjoh3.shinyapps.io/georefr/

**Comment by MarijaStanojcic** [comment]
I see this is still open, and I am encountering the same issue. My app works fine locally and on shinyapps.io, but I'm also getting the same error as @mrjoh3. Any advice?

**Comment by betatim** [comment]
Hi there 👋!

Can we move this discussion to http://discourse.jupyter.org/ (where most of the people who hang out here also hang out, as well as more people). We are trying to streamline the [different discussion places](https://discourse.jupyter.org/t/a-proposal-for-jupyterhub-communications/505) and want to use the issues on GitHub repos for technical discussions on how to change the contents of the repo. More general discussions should go to discourse so that they are easier to find, better indexed by google and generally more accessible than being hidden in the bowls of a GitHub repository ;)

Thanks!
