### ISSUE TITLE
RStudio not working with repo2docker

### ISSUE THREAD

**Issue by RaoOfPhysics** [binder-examples/r#14]
[I'm not sure if this is the right place to file this issue, so please point me to the best repo in which to do so.]

I pulled the latest version of this repo to my machine and ran `jupyter-repo2docker .`. The container got built successfully and I received the token to launch the Jupyter notebooks. However, when I tried going to `New` &rarr; `RStudio Session`, I got the following error:

![screen shot 2018-07-14 at 10 37 24](https://user-images.githubusercontent.com/7623019/42722769-35346946-8752-11e8-9d25-cd722cb1e478.png)

This was, I think, the relevant error on the console:

```bash
14 Jul 2018 08:36:23 [rsession-achintya] ERROR system error 13 (Permission denied) [message=User 'achintya' has id 501, which is lower than the minimum user id of 1000 (this is controlled by the the auth-minimum-user-id rserver option)];
OCCURRED AT: int main(int, char* const*) /home/ubuntu/rstudio/src/cpp/session/SessionMain.cpp:1631; LOGGED FROM: int main(int, char* const*) /home/ubuntu/rstudio/src/cpp/session/SessionMain.cpp:1639
```

What's the best way to resolve this without tinkering with one's system configuration?

**Comment by betatim** [comment]
Run `repo2docker` with the `--user-id` option. We by default set the user ID in the container to the user ID of your local user. This works most of the time and means when you mount directories from the host into the container all permissions are right. However lots of tools require your user ID to be 1000 or larger. So I'd suggest `--user-id 1000` as command line flag.

**Comment by RaoOfPhysics** [comment]
Ah ha! I need to read the documentation more carefully. Testing now!

**Comment by RaoOfPhysics** [comment]
Works! But doesn't seem to mount the local directory.

@betatim: Should I open a different issue for this?

**Comment by choldgraf** [comment]
Can you provide a link to the repo?

**Comment by RaoOfPhysics** [comment]
@choldgraf: It's this repo cloned to my machine. :) What's the procedure for mounting the local directory? `-v .:.` or `-v .:~` or something else? I'll admit I was a little tired when I was tinkering, so might've missed something fairly obvious.

**Comment by betatim** [comment]
To mount the local directory (containing the repo) into your container have a read of [repo2docker for local repos](https://github.com/Build-a-binder/build-a-binder.github.io/blob/master/workshop/20-repo2docker.md#repo2docker-for-local-repositories) which if you like it can be turned into real docs.

(But I think it is a bug in repo2docker that if you run `repo2docker local/path/to/repo` it isn't automatically mounted. Something for the repo2docker issue tracker.)

**Comment by RaoOfPhysics** [comment]
@betatim: This would be ace to include in the main instructions for the `-v` flag. See, my use-case for binder would then be to run my repo locally with `repo2docker` to test that my environment etc. works well and then push it to GH for binder. "Guarantees" reproducibility. Does this make sense to you?

BTW, if you've `cd`'d into the repo in which you want to run `repo2docker`, it's easier to run:

```bash
repo2docker .
```

**Comment by betatim** [comment]
Yes, running things locally, from day one before you even ponder sharing is exactly the use case for `repo2docker`. Which is why I think it is a bug that the "using a local directory" story is so convoluted.
