### ISSUE TITLE
Shiny dashboards no longer rendering

### ISSUE THREAD

**Issue by bentut** [binder-examples/r#17]
I am using the Shiny feature to render dashboards. The shiny link shown here was working for me about a week and a half ago, but it's not working now: https://github.com/binder-examples/r
http://beta.mybinder.org/v2/gh/binder-examples/r/master?urlpath=shiny/bus-dashboard/

**Comment by RaoOfPhysics** [comment]
Can confirm: it redirects to `https://hub.mybinder.org/hub/bus-dashboard/?token=[something-or-the-other]` and says there's nothing to be found on that page.

**Comment by betatim** [comment]
Fixed now. Thanks for reporting!

We had a bug in how we handle trailing (or missing) `/`es in the URLs.
