### ISSUE TITLE
R example not working when copied to personal repo

### ISSUE THREAD

**Issue by bentut** [binder-examples/r#18]
I cloned the binder-example/r repo on my own github and updated the binder badge to point at my new repo instead of the original one and the load is crapping out.
https://github.com/binder-examples/r (works)
https://github.com/bentut/bdac-grad (error- clone of above)

This worked for me last week

**Comment by RaoOfPhysics** [comment]
Just tested it and https://mybinder.org/v2/gh/bentut/bdac-grad/master?filepath=index.ipynb seems to work fine!

Although, initially, it spent ages spinning up without launching the image. It took a second try to get it to load promptly from the pre-built image.

**Comment by choldgraf** [comment]
@bentut could you confirm that this does (or doesn't) work for you now?

**Comment by bentut** [comment]
@choldgraf yes, this works for me now! thank you!
