### ISSUE TITLE
Should we add an example for DESCRIPTION?

### ISSUE THREAD

**Issue by betatim** [binder-examples/r#19]
Maybe create a new repository instead of using this one.

@gedankenstuecke just added [support for `DESCRIPTION` files to repo2docker](https://github.com/jupyter/repo2docker/pull/406)

**Comment by betatim** [comment]
I'd add a notebook and two badges to the README (normal launch badge and one directly to RStudio).

Can we move it to this organisation as well?

**Comment by gedankenstuecke** [comment]
Ok, I added the badges & the example repo to https://github.com/gedankenstuecke/binder-r-description 

I tried moving it to the `binder-examples` org, but I lack permissions for doing so. 😄

**Comment by betatim** [comment]
You should have an invite to upgrade your privileges.

**Comment by gedankenstuecke** [comment]
Thanks! it now resides under https://github.com/binder-examples/binder-r-description 🎉
