### ISSUE TITLE
Howto install additional linux packages now that runtime.txt replaces docker file

### ISSUE THREAD

**Issue by statOmics** [binder-examples/r#21]
Great resource! 
For a teaching project, we need to install an R/Bioconductor package that requires the libnetcdf-dev linux package. I was wondering how to do that as there is no docker anymore. Is the runtime.txt approach compatible with a docker file? 

Thx,

Lieven

**Comment by choldgraf** [comment]
Give a shot at `apt.txt` or you can try installing it manually with a `postBuild` file!

https://mybinder.readthedocs.io/en/latest/config_files.html

**Comment by statOmics** [comment]
Great! apt.txt did the job.

**Comment by choldgraf** [comment]
woot! 🎉
