### ISSUE TITLE
Unable to install tmap and tmap dependencies

### ISSUE THREAD

**Issue by RAJohansen** [binder-examples/r#23]
Following the example, I expected that all I would have to do install tmap would be to use the following in my install.R file:

install.packages('tmap')

However, when I open the notebook, I receive the following error:

Error in library(tmap): there is no package called ‘tmap’
Traceback:
1. library(tmap)
2. stop(txt, domain = NA)

I have tried many variations but none have been successful.
https://github.com/RAJohansen/BindeR 

Any ideas?

**Comment by choldgraf** [comment]
hmmm, have you tried posting something to the jupyter Discourse? (discourse.jupyter.org) I think it has more eyeballs than this repository so you might have better luck finding an answer there!

**Comment by cboettig** [comment]
@RAJohansen `tmap` has some pretty heavy and specific dependencies on system libraries (in particular, relatively recent versions of gdal, proj, geos, e.g. see https://github.com/rocker-org/geospatial/blob/master/Dockerfile).  I don't recall of hand if these are available in the apt repos used on the base image used by binder (@choldgraf is that 18.04?)   

One option is to use the `rocker/binder` image: https://github.com/rocker-org/binder, where the spatial libraries are already installed.

**Comment by choldgraf** [comment]
yep, it's 18.04! Giving a shot at using Rocker sounds like a good idea to me, if you're willing to write a bit of your own Dockerfile!

**Comment by RAJohansen** [comment]
Using the rocker dockerfile worked, thank you!
