### ISSUE TITLE
install.R does not appear to run when launching the RStudio instance

### ISSUE THREAD

**Issue by RaoOfPhysics** [binder-examples/r#7]
If you head to http://beta.mybinder.org/v2/gh/binder-examples/r/master?urlpath=rstudio from the README file and try to play with `index.Rmd`, you get an error when attempting to execute the first code chunk:

```markdown
Error in library(ggplot2) : there is no package called ‘ggplot2’
```

It seems that the packages from `install.R` don't get installed when launching the RStudio instance.

If I first run `install.R` within RStudio (running `source("install.R")` in the Console, the error message doesn't appear and all works well.

Can this file be made to run when the RStudio instance is launched?

**Comment by choldgraf** [comment]
hey @RaoOfPhysics - I think you actually caught the same bug that I noticed a couple days ago :-)

I added an issue about in the repo2docker repo here: https://github.com/jupyter/repo2docker/issues/237

Feel free to chime in there!

**Comment by RaoOfPhysics** [comment]
Hey, @choldgraf. Yup, I already commented there: https://github.com/jupyter/repo2docker/issues/237#issuecomment-366813692 Should probably close this issue then and re-direct conversations to the `repo2docker` thread. :)
