### ISSUE TITLE
Is there a way to set the R version?

### ISSUE THREAD

**Issue by cboettig** [binder-examples/r#9]
Ideally binder would just match the R version current with the MRAN date (likewise for the RStudio version; this is what we do in Rocker: https://github.com/rocker-org/rocker-versioned/blob/master/VERSIONS.md)  Are you installing R from default Ubuntu repos, CRAN-hosted Ubuntu binaries, or from source?

**Comment by choldgraf** [comment]
Think you could chime in over here: https://github.com/jupyter/repo2docker/issues/245

This is something we'd definitely like to figure out!

**Comment by taylorreiter** [comment]
Has there been any forward movement on this? We would love to be able to change our R install!

**Comment by cboettig** [comment]
@taylorreiter there's always the option of using the `rocker/binder` images if you don't mind adding a Dockerfile (i.e. copy-paste from a template), see: https://github.com/rocker-org/binder.  Just specify the R version in the `FROM` line, e.g.

```
FROM rocker/binder:3.5.2
```

**Comment by taylorreiter** [comment]
Wonderful! Thank you @cboettig!

**Comment by 0lorak** [comment]
Many thanks @cboettig. This is really helpful.

**Comment by sje30** [comment]
+1 for specifying the r version for our tool @nuest @innovationchef

**Comment by choldgraf** [comment]
@betatim has been pushing on implementing R version support here: https://github.com/jupyter/repo2docker/pull/772

would love thoughts from people!

**Comment by betatim** [comment]
Let's close this issue as the right place for discussion is the repo2docker repository and where Chris linked to.
